version: '2'

services:
    nginx:
        restart: always
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        environment:
            - PORT=8000
        ports:
            - "8000:8000"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/home/forafekt/apps/src/static
        container_name: mlnginx
    wsgiserver:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /home/forafekt/apps/docker/backend/wsgi-entrypoint.sh
        # stdin_open: true  # docker run -i
        # tty: true         # docker run -t
        volumes:
            - venv:/home/forafekt/apps/ml-venv
            - static_volume:/home/forafekt/apps/src/static
        expose:
            - 8000
        container_name: mlbackend
volumes:
    static_volume: {}
    venv:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./ml-venv